language: node_js

node_js:
  - "13"

services:
  - docker

jobs:
  include:
    - stage: Validate
      name: test
      script: source bin/env && make test
    - name: lint
      script: source bin/env && make lint

    - stage: Build
      name: build-image
      script: source bin/env && make build
