language: node_js

node_js:
  - "13"

services:
  - docker

jobs:
  include:
    - stage: Validate
      name: test
      script: npm run test
    - name: lint
      script: npm run lint

    - stage: Build
      name: build-image
      script: make build
