version: "3.7"

services:
  dev:
    user: root
    image: gcr.io/${PROJECT_ID}/${IMAGE}
    build: .
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8080:8080"
    env_file:
      - envs/.env.local
